name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Verify JAR file exists
        run: ls -la build/libs

      - name: Docker build
        run: docker build . -t demo:latest

  publish-hello-docker-image:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
  uses: docker/login-action@v1
  with:
  registry: ghcr.io
  username: ${{ github.actor }}
  password: ${{ secrets.GITHUB_TOKEN }}
              - name: Build the hello-docker Docker image
  run: |
    docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
    docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
    docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest
